---
- name: Install Python devel packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-dev
    - python-pip
    - python-setuptools

- name: Install OpenstackClients
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - python-keystoneclient==0.11.2
    - python-novaclient==2.20.0

- name: Update distribute, fixes version problems with nova
  command: pip install --upgrade distribute

- name: Install Heartbeat OpenStack script
  copy:
    src: FloatingIP
    dest: /usr/lib/ocf/resource.d/heartbeat/FloatingIP
    owner: root
    group: root
    mode: 0755

- name: Install Heartbeat OpenStack wrapper script
  copy:
    src: FloatingIP-wrapper
    dest: /etc/heartbeat/resource.d/FloatingIP
    owner: root
    group: root
    mode: 0755

- name: Create the OpenStack configuration directory
  file:
    path: /etc/openstack
    state: directory
    owner: root
    group: root

- name: Install OpenStack configuration file
  template:
    src: nova.conf.j2
    dest: /etc/openstack/nova.conf
    owner: root
    group: root
    mode: 0600
  notify: restart heartbeat
